### ISSUE TITLE
Script stop without error but final output files are not generated

### ISSUE THREAD

**Issue by Enorya** [laczkol/RADOrgMiner#2]
Hello,

I am trying to use your script but when I use it on your example dataset it seems the script stop before the end but I don't have any error message.
This is the end of the log file:
```bash
Subsetting bed loci with a subsampling proportion of 1.0
bed regions with a minimum bed coverage of 15 are:
NC_000932.1     1183    1700
NC_000932.1     16906   17868
NC_000932.1     32398   33473
NC_000932.1     33592   34562
NC_000932.1     52616   53705
NC_000932.1     80867   81856
NC_000932.1     83310   84206
NC_000932.1     97333   98493
NC_000932.1     121345  122411
lyr_KU764768_TGCA
lyr_KX886355_TGCA
thal_MK380719_TGCA
thal_MK380720_TGCA
thal_MK380721_TGCA
lyr_NC_034379_TGCA
```
Looking at your script I managed to find that the script seems to have a problem after the line 637 because I have the bed_loci/ folder with some files in it. However, the name of the files in this folder are weird: `loc_NC_000932.1:1183-1700?0?517`. I think the tabulations which should be in the place of the interrogation points are not correctly interpreted. I assume the lines 640, 641 and 642 should have change the names of those files but it seems it's not working. Didn't you mix up the sed and rename commands? Because I checked and the rename command don't work with this kind of structure: `'s/\t/_/'`

Thank you in advance for your help!

**Comment by laczkol** [comment]
Hi,
thank you for reaching out and finding an important error. You are exactly right about the rename command. I mistreated it and does not work like that on every system. On my computer, I have perl-rename installed, but that is not a standard part of every Linux distribution. I now rewrote the corresponding part to use `sed` and `mv` instead. The script seems to run alright for me and should be less sensitive to different environments.
Could you please clone the repository again and try the updated script?
Please, let me know if you need further help.

**Comment by Enorya** [comment]
Hi,
It's working perfectly now, thank you!
